# Flask settings

FLASK_DEBUG = False  # Do not use debug mode in production

FLASK_SERVER_HOST = '0.0.0.0'
FLASK_SERVER_HOST_DEBUG = '127.0.0.1'
FLASK_SERVER_PORT = '80'
FLASK_SERVER_PORT_DEBUG = '4995'

# Flask-Restplus settings
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False

# SQLAlchemy settings
SQLALCHEMY_DATABASE_HOST = '_SQLALCHEMY_DATABASE_HOST_'
SQLALCHEMY_DATABASE_PORT = '_SQLALCHEMY_DATABASE_PORT_'
SQLALCHEMY_DATABASE_DATABASE = '_SQLALCHEMY_DATABASE_DATABASE_'
SQLALCHEMY_DATABASE_USER = '_SQLALCHEMY_DATABASE_USER_'
SQLALCHEMY_DATABASE_PASSWORD = '_SQLALCHEMY_DATABASE_PASSWORD_'
SQLALCHEMY_DATABASE_URI = 'postgresql://{}:{}@{}:{}/{}'
SQLALCHEMY_TRACK_MODIFICATIONS = False

# ___________________ BC Setting ____________________


ITPS_SERVICE_ADDRESS = '_ITPS_SERVICE_ADDRESS_'
ITPS_SERVICE_PRIVATE_KEY = '_ITPS_SERVICE_PRIVATE_KEY_'

NODE_PROTOCOL = '_NODE_PROTOCOL_'
NODE_PORT = '_NODE_PORT_'
NODE_HOST = '_NODE_HOST_'
INFURA_NODE_HOST = '_INFURA_NODE_HOST_'
USE_INFURA = _USE_INFURA_
INFURA_PROTOCOL = '_INFURA_PROTOCOL_'



ADPCHANNEL_MANAGER_ADDRESS = '_ADPCHANNEL_MANAGER_ADDRESS_'
ADPCHANNEL_MANAGER_JSON = 'ADPChannelManager.json'
ADPCHANNEL_JSON = 'ADPChannel.json'
ERC20_TOKEN_JSON = 'ERC20Token.json'



CLIENT_SYSTEM_ADDRESS = '_CLIENT_SYSTEM_ADDRESS_'
TRX_GRACETIME = _TRX_GRACETIME_

GAS_PRICE = _GAS_PRICE_
# GAS_PRICE * 1000
GAS_LIMIT_CHANNEL_CREATION = _GAS_LIMIT_CHANNEL_CREATION_
GAS_LIMIT_WITHDRAW = _GAS_LIMIT_WITHDRAW_
GAS_LIMIT_SETTLEMENT = _GAS_LIMIT_SETTLEMENT_
GAS_LIMIT_TRANSFER = _GAS_LIMIT_TRANSFER_

TRX_FAILED_RETRY = 3

EMPTY_CHANNEL = '0x0000000000000000000000000000000000000000'
TRANSFER_EVENT_NAME = 'Transfer'
SETTLEMENT_EVENT_NAME = 'Settlement'
TOKEN_DEPOSIT_EVENT_NAME = "token_deposit"
TOKEN_WITHDRAW_EVENT_NAME = "token_withdrawal"

BC_MONITOR_INTERVAL = _BC_MONITOR_INTERVAL_

SCHEDULED_SETTLEMENT_INTERVAL = _SCHEDULED_SETTLEMENT_INTERVAL_
MIN_SETTLEMENT_AMOUNT = _MIN_SETTLEMENT_AMOUNT_
AUTO_SETTLEMENT_AMOUNT = _AUTO_SETTLEMENT_AMOUNT_


SEND_CALLBACK = _SEND_CALLBACK_

SCHEDULED_SETTLEMENT_PERIOD = _SCHEDULED_SETTLEMENT_PERIOD_

# _________________________________Debug Settings_______________________
TRANSFER_AMOUNT = 100

RUN_MONITOR = _RUN_MONITOR_

CLIENT_SYSTEM_BASE_PROTOCOL = '_CLIENT_SYSTEM_BASE_PROTOCOL_'
CLIENT_SYSTEM_BASE_URL = '_CLIENT_SYSTEM_BASE_URL_'
CLIENT_SYSTEM_BASE_PORT = '_CLIENT_SYSTEM_BASE_PORT_'
CLIENT_SYSTEM_CHANNEL_STATE_URL = '_CLIENT_SYSTEM_CH_STATE_URL_'
